mongo_db_username = "jsboothalingam90"
mongo_db_password = "CEw6m4YvDEQWzGQr"
sql_conn_string = "Driver={SQL Server Native Client 11.0};Server=tcp:youtubedata.database.windows.net,1433;Database=youtubedataharvestingandwarhousing;Uid=sayoutubedata;Pwd=Boobesh@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"